include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build_container
  - build
  - test

build_cuda_image:
  extends: .container-builder-dynamic-name
  stage: build_container
  timeout: 2h
  variables:
    DOCKERFILE: ci/base_cuda.Dockerfile
    WATCH_FILECHANGES: ci/base_cuda.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/bipp/bipp-ci
    DOCKER_BUILD_ARGS: '["cuda_arch=60", "cpu_arch=haswell", "spack_arch=haswell"]'

build_library:
  extends: .container-builder
  needs: ["build_cuda_image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/bipp/bipp-ci:$CI_COMMIT_SHA
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}"]'

run_unit_tests:
  extends: .container-runner-daint-gpu
  needs: ["build_library"]
  stage: test
  script:
    - source /etc/profile.d/z10_spack_environment.sh
    - source /etc/profile.d/z11_paths.sh
    - /src/build_cuda/tests/run_tests
  image: $CSCS_REGISTRY_PATH/bipp/bipp-ci:$CI_COMMIT_SHA
  variables:
    CRAY_CUDA_MPS: 0
    GIT_STRATEGY: none
    MPICH_MAX_THREAD_SAFETY: multiple
    CSCS_REGISTRY_LOGIN: 'YES'
    PULL_IMAGE: 'YES'
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_UNBUFFEREDIO: ''
    SLURM_WAIT: 0
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "30:00"


run_python_examples:
  extends: .container-runner-daint-gpu
  needs: ["build_library"]
  stage: test
  script:
    - source /etc/profile.d/z10_spack_environment.sh
    - source /etc/profile.d/z11_paths.sh
    - cd /src/examples/simulation
    - python3 lofar_bootes_ss.py
    - python3 lofar_bootes_nufft.py
  image: $CSCS_REGISTRY_PATH/bipp/bipp-ci:$CI_COMMIT_SHA
  variables:
    CRAY_CUDA_MPS: 0
    GIT_STRATEGY: none
    MPICH_MAX_THREAD_SAFETY: multiple
    CSCS_REGISTRY_LOGIN: 'YES'
    PULL_IMAGE: 'YES'
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_UNBUFFEREDIO: ''
    SLURM_WAIT: 0
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "30:00"




